### ISSUE TITLE
Add ca-certificates to ubuntu24/fb_vanilla_ub24–50.sh

### ISSUE THREAD

**Issue by NickBarrett** [IBSurgeon/firebirdlinuxinstall#3]
Hi there,

Thanks for the great project. We've had great success installing vanilla Firebird v5 on Ubuntu 24.04 with your script.

We did have to make an alteration to line 36 though. Without the addition of `ca-certificates` to the call to `apt install`, the later call to `curl` would fail verifying ssl cert to get [Firebird](https://github.com/FirebirdSQL/firebird/releases/download/v5.0.0/Firebird-5.0.0.1306-0-linux-x64.tar.gz).

We are running your script within the official ubuntu:24.04 image.

Thanks again,

Nick

**Comment by alexeykovyazin** [comment]
Thank you, it was resolved in the recent update.
